name = "QualitativeNetworks"
uuid = "ba61d19f-daf7-42ed-91ab-e8e04fc92a6d"
version = "0.0.1"
authors = ["Reuben Gardos Reid <5456207+ReubenJ@users.noreply.github.com>"]

[deps]
GraphDynamicalSystems = "13529e2e-ed53-56b1-bd6f-420b01fca819"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
