name = "GraphDynamicalSystems"
uuid = "13529e2e-ed53-56b1-bd6f-420b01fca819"
version = "0.0.9"
authors = ["Reuben Gardos Reid <5456207+ReubenJ@users.noreply.github.com>"]

[workspace]
projects = ["test"]

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "3.47,4.10"
julia = "1.10"
